
import { Workflow } from "@/types/workflow";

export const mockWorkflows: Workflow[] = [
  {
    id: '1',
    name: 'Boas-vindas ao Cliente',
    description: 'Envia e-mail e WhatsApp quando um novo cliente se cadastra.',
    type: 'notificacao',
    status: 'ativo',
    owner: 'Admin',
    nodes: [],
    connections: [],
    updatedAt: '2024-03-15T10:00:00Z',
    createdAt: '2024-03-01T08:00:00Z',
  },
  {
    id: '2',
    name: 'Aprovação de Reembolso',
    description: 'Fluxo para aprovação de solicitações de reembolso financeiro.',
    type: 'aprovacao',
    status: 'pausado',
    owner: 'Financeiro',
    nodes: [],
    connections: [],
    updatedAt: '2024-03-14T15:30:00Z',
    createdAt: '2024-02-15T09:00:00Z',
  },
  {
    id: '3',
    name: 'Sincronização CRM -> ERP',
    description: 'Mantém os dados de clientes atualizados entre as plataformas.',
    type: 'integracao',
    status: 'ativo',
    owner: 'Sistemas',
    nodes: [],
    connections: [],
    updatedAt: '2024-03-15T11:45:00Z',
    createdAt: '2024-01-20T14:00:00Z',
  },
  {
    id: '4',
    name: 'Triagem de Suporte',
    description: 'Classifica chamados por prioridade e atribui a técnicos.',
    type: 'atendimento',
    status: 'rascunho',
    owner: 'Suporte',
    nodes: [],
    connections: [],
    updatedAt: '2024-03-10T16:20:00Z',
    createdAt: '2024-03-10T10:00:00Z',
  },
  {
    id: '5',
    name: 'Limpeza Semanal de Leads',
    description: 'Remove leads inativos e consolida dados de conversão.',
    type: 'dados',
    status: 'ativo',
    owner: 'Marketing',
    nodes: [],
    connections: [],
    updatedAt: '2024-03-11T02:00:00Z',
    createdAt: '2024-02-28T22:00:00Z',
  },
  {
    id: '6',
    name: 'Alertas de Estoque Baixo',
    description: 'Notifica a gerência quando produtos atingem nível crítico.',
    type: 'notificacao',
    status: 'ativo',
    owner: 'Estoque',
    nodes: [],
    connections: [],
    updatedAt: '2024-03-14T09:15:00Z',
    createdAt: '2023-12-15T11:00:00Z',
  },
  {
    id: '7',
    name: 'Recuperação de Carrinho',
    description: 'Fluxo para recuperar vendas abandonadas via cupom.',
    type: 'automacao',
    status: 'ativo',
    owner: 'E-commerce',
    nodes: [],
    connections: [],
    updatedAt: '2024-03-15T12:00:00Z',
    createdAt: '2024-01-10T08:00:00Z',
  },
  {
    id: '8',
    name: 'Processamento de Notas Fiscais',
    description: 'Extrai dados de PDFs e insere no banco de dados.',
    type: 'dados',
    status: 'pausado',
    owner: 'Contabilidade',
    nodes: [],
    connections: [],
    updatedAt: '2024-03-12T17:40:00Z',
    createdAt: '2024-02-05T13:00:00Z',
  },
  {
    id: '9',
    name: 'Onboarding de Colaboradores',
    description: 'Sequência de e-mails e acessos para novos contratados.',
    type: 'automacao',
    status: 'arquivado',
    owner: 'RH',
    nodes: [],
    connections: [],
    updatedAt: '2024-02-01T10:00:00Z',
    createdAt: '2023-10-15T09:00:00Z',
  },
  {
    id: '10',
    name: 'Integração Shopify -> Stripe',
    description: 'Sincroniza pagamentos e pedidos em tempo real.',
    type: 'integracao',
    status: 'ativo',
    owner: 'Sistemas',
    nodes: [],
    connections: [],
    updatedAt: '2024-03-15T13:20:00Z',
    createdAt: '2024-03-01T15:00:00Z',
  },
  {
    id: '11',
    name: 'Pesquisa de Satisfação NPS',
    description: 'Envia pesquisa após 7 dias da entrega do produto.',
    type: 'notificacao',
    status: 'ativo',
    owner: 'Sucesso do Cliente',
    nodes: [],
    connections: [],
    updatedAt: '2024-03-15T08:30:00Z',
    createdAt: '2024-02-20T11:00:00Z',
  },
  {
    id: '12',
    name: 'Validação de Documentos KYC',
    description: 'Fluxo automático para verificação de identidade.',
    type: 'aprovacao',
    status: 'ativo',
    owner: 'Segurança',
    nodes: [],
    connections: [],
    updatedAt: '2024-03-15T14:00:00Z',
    createdAt: '2024-03-05T09:00:00Z',
  },
];
