
import { WorkflowModuleDefinition } from "@/types/workflow";

export const workflowModules: WorkflowModuleDefinition[] = [
  // Gatilhos
  {
    id: 'webhook',
    type: 'trigger',
    category: 'gatilhos',
    title: 'Webhook',
    description: 'Receber dados de serviço externo',
    icon: 'Webhook',
    color: 'emerald',
    supportedFlowTypes: ['automacao', 'integracao', 'dados'],
  },
  {
    id: 'agendamento',
    type: 'trigger',
    category: 'gatilhos',
    title: 'Agendamento',
    description: 'Executar em horários específicos',
    icon: 'Clock',
    color: 'emerald',
    supportedFlowTypes: ['automacao', 'notificacao', 'dados'],
  },
  {
    id: 'evento-formulario',
    type: 'trigger',
    category: 'gatilhos',
    title: 'Evento de formulário',
    description: 'Quando um formulário é enviado',
    icon: 'FileText',
    color: 'emerald',
    supportedFlowTypes: ['automacao', 'aprovacao'],
  },
  {
    id: 'novo-cadastro',
    type: 'trigger',
    category: 'gatilhos',
    title: 'Novo cadastro',
    description: 'Quando um novo usuário se cadastra',
    icon: 'UserPlus',
    color: 'emerald',
    supportedFlowTypes: ['automacao', 'notificacao'],
  },
  {
    id: 'alteracao-status',
    type: 'trigger',
    category: 'gatilhos',
    title: 'Alteração de status',
    description: 'Quando um status de registro muda',
    icon: 'RefreshCw',
    color: 'emerald',
    supportedFlowTypes: ['automacao', 'aprovacao'],
  },
  {
    id: 'upload-arquivo',
    type: 'trigger',
    category: 'gatilhos',
    title: 'Upload de arquivo',
    description: 'Quando um novo arquivo é enviado',
    icon: 'Upload',
    color: 'emerald',
    supportedFlowTypes: ['automacao', 'dados'],
  },
  {
    id: 'recebimento-email',
    type: 'trigger',
    category: 'gatilhos',
    title: 'Recebimento de e-mail',
    description: 'Quando um e-mail é recebido',
    icon: 'Mail',
    color: 'emerald',
    supportedFlowTypes: ['automacao', 'atendimento'],
  },
  {
    id: 'novo-pedido',
    type: 'trigger',
    category: 'gatilhos',
    title: 'Novo pedido',
    description: 'Quando uma nova venda é realizada',
    icon: 'ShoppingCart',
    color: 'emerald',
    supportedFlowTypes: ['automacao', 'notificacao', 'dados'],
  },
  {
    id: 'novo-lead',
    type: 'trigger',
    category: 'gatilhos',
    title: 'Novo lead',
    description: 'Quando um novo potencial cliente é capturado',
    icon: 'Users',
    color: 'emerald',
    supportedFlowTypes: ['automacao', 'atendimento'],
  },
  {
    id: 'trigger-manual',
    type: 'trigger',
    category: 'gatilhos',
    title: 'Trigger manual',
    description: 'Executar clicando em um botão',
    icon: 'Play',
    color: 'emerald',
    supportedFlowTypes: ['automacao', 'aprovacao', 'notificacao', 'integracao', 'atendimento', 'dados'],
  },

  // Ações
  {
    id: 'enviar-email',
    type: 'action',
    category: 'acoes',
    title: 'Enviar e-mail',
    description: 'Enviar mensagem por correio eletrônico',
    icon: 'Send',
    color: 'blue',
    supportedFlowTypes: ['automacao', 'notificacao', 'atendimento'],
  },
  {
    id: 'enviar-whatsapp',
    type: 'action',
    category: 'acoes',
    title: 'Enviar WhatsApp',
    description: 'Enviar mensagem pelo WhatsApp',
    icon: 'MessageSquare',
    color: 'blue',
    supportedFlowTypes: ['automacao', 'notificacao', 'atendimento'],
  },
  {
    id: 'enviar-sms',
    type: 'action',
    category: 'acoes',
    title: 'Enviar SMS',
    description: 'Enviar mensagem de texto curta',
    icon: 'Smartphone',
    color: 'blue',
    supportedFlowTypes: ['automacao', 'notificacao'],
  },
  {
    id: 'criar-tarefa',
    type: 'action',
    category: 'acoes',
    title: 'Criar tarefa',
    description: 'Adicionar nova tarefa ao sistema',
    icon: 'CheckSquare',
    color: 'blue',
    supportedFlowTypes: ['automacao', 'aprovacao', 'atendimento'],
  },
  {
    id: 'atualizar-registro',
    type: 'action',
    category: 'acoes',
    title: 'Atualizar registro',
    description: 'Modificar dados de um registro existente',
    icon: 'Edit',
    color: 'blue',
    supportedFlowTypes: ['automacao', 'dados', 'integracao'],
  },
  {
    id: 'criar-registro',
    type: 'action',
    category: 'acoes',
    title: 'Criar registro',
    description: 'Adicionar novo registro ao banco de dados',
    icon: 'PlusCircle',
    color: 'blue',
    supportedFlowTypes: ['automacao', 'dados', 'integracao'],
  },
  {
    id: 'chamar-api',
    type: 'action',
    category: 'acoes',
    title: 'Chamar API',
    description: 'Fazer requisição para serviço externo',
    icon: 'Globe',
    color: 'blue',
    supportedFlowTypes: ['automacao', 'integracao', 'dados'],
  },
  {
    id: 'gerar-documento',
    type: 'action',
    category: 'acoes',
    title: 'Gerar documento',
    description: 'Criar PDF ou arquivo a partir de dados',
    icon: 'FileCode',
    color: 'blue',
    supportedFlowTypes: ['automacao', 'aprovacao'],
  },
  {
    id: 'registrar-log',
    type: 'action',
    category: 'acoes',
    title: 'Registrar log',
    description: 'Gravar histórico de execução',
    icon: 'List',
    color: 'blue',
    supportedFlowTypes: ['automacao', 'dados', 'integracao'],
  },
  {
    id: 'criar-protocolo',
    type: 'action',
    category: 'acoes',
    title: 'Criar protocolo',
    description: 'Gerar número de atendimento',
    icon: 'Hash',
    color: 'blue',
    supportedFlowTypes: ['atendimento'],
  },
  {
    id: 'atualizar-crm',
    type: 'action',
    category: 'acoes',
    title: 'Atualizar CRM',
    description: 'Sincronizar dados com o CRM',
    icon: 'Database',
    color: 'blue',
    supportedFlowTypes: ['automacao', 'atendimento'],
  },
  {
    id: 'criar-usuario',
    type: 'action',
    category: 'acoes',
    title: 'Criar usuário',
    description: 'Adicionar novo acesso ao sistema',
    icon: 'UserPlus',
    color: 'blue',
    supportedFlowTypes: ['automacao'],
  },
  {
    id: 'notificacao-interna',
    type: 'action',
    category: 'acoes',
    title: 'Notificação interna',
    description: 'Alertar equipe via dashboard',
    icon: 'Bell',
    color: 'blue',
    supportedFlowTypes: ['automacao', 'aprovacao', 'notificacao'],
  },

  // Condições
  {
    id: 'se-entao',
    type: 'condition',
    category: 'condicoes',
    title: 'Se / então',
    description: 'Ramificar fluxo baseado em condição',
    icon: 'Split',
    color: 'amber',
    supportedFlowTypes: ['automacao', 'aprovacao', 'notificacao', 'integracao', 'atendimento', 'dados'],
  },
  {
    id: 'comparacao-valor',
    type: 'condition',
    category: 'condicoes',
    title: 'Comparação de valor',
    description: 'Verificar se valores são iguais ou diferentes',
    icon: 'Binary',
    color: 'amber',
    supportedFlowTypes: ['automacao', 'dados'],
  },
  {
    id: 'verificacao-status',
    type: 'condition',
    category: 'condicoes',
    title: 'Verificação de status',
    description: 'Checar estado atual do registro',
    icon: 'ShieldCheck',
    color: 'amber',
    supportedFlowTypes: ['automacao', 'aprovacao'],
  },
  {
    id: 'campo-vazio',
    type: 'condition',
    category: 'condicoes',
    title: 'Verificação de campo vazio',
    description: 'Verificar preenchimento de campos',
    icon: 'Eraser',
    color: 'amber',
    supportedFlowTypes: ['automacao', 'dados'],
  },
  {
    id: 'verificacao-data',
    type: 'condition',
    category: 'condicoes',
    title: 'Verificação de data',
    description: 'Validar prazos e períodos',
    icon: 'Calendar',
    color: 'amber',
    supportedFlowTypes: ['automacao', 'aprovacao'],
  },
  {
    id: 'verificacao-permissao',
    type: 'condition',
    category: 'condicoes',
    title: 'Verificação de permissão',
    description: 'Checar nível de acesso do usuário',
    icon: 'Lock',
    color: 'amber',
    supportedFlowTypes: ['automacao', 'aprovacao'],
  },
  {
    id: 'roteamento-prioridade',
    type: 'condition',
    category: 'condicoes',
    title: 'Roteamento por prioridade',
    description: 'Direcionar por nível de importância',
    icon: 'ArrowUpRight',
    color: 'amber',
    supportedFlowTypes: ['atendimento'],
  },
  {
    id: 'roteamento-canal',
    type: 'condition',
    category: 'condicoes',
    title: 'Roteamento por canal',
    description: 'Direcionar por canal de origem',
    icon: 'GitBranch',
    color: 'amber',
    supportedFlowTypes: ['atendimento'],
  },
  {
    id: 'verificacao-booleana',
    type: 'condition',
    category: 'condicoes',
    title: 'Verificação booleana',
    description: 'Verificar verdadeiro ou falso',
    icon: 'ToggleLeft',
    color: 'amber',
    supportedFlowTypes: ['automacao', 'dados'],
  },

  // Dados
  {
    id: 'consulta-banco',
    type: 'action',
    category: 'dados',
    title: 'Consulta ao banco',
    description: 'Buscar informações no banco de dados',
    icon: 'Search',
    color: 'purple',
    supportedFlowTypes: ['dados', 'integracao'],
  },
  {
    id: 'insercao-banco',
    type: 'action',
    category: 'dados',
    title: 'Inserção em banco',
    description: 'Adicionar novos dados ao banco',
    icon: 'Database',
    color: 'purple',
    supportedFlowTypes: ['dados', 'integracao'],
  },
  {
    id: 'atualizacao-banco',
    type: 'action',
    category: 'dados',
    title: 'Atualização em banco',
    description: 'Modificar registros existentes',
    icon: 'Save',
    color: 'purple',
    supportedFlowTypes: ['dados', 'integracao'],
  },
  {
    id: 'remocao-banco',
    type: 'action',
    category: 'dados',
    title: 'Remoção em banco',
    description: 'Excluir registros do banco',
    icon: 'Trash2',
    color: 'purple',
    supportedFlowTypes: ['dados'],
  },
  {
    id: 'buscar-cliente',
    type: 'action',
    category: 'dados',
    title: 'Buscar cliente',
    description: 'Localizar cadastro de cliente',
    icon: 'UserSearch',
    color: 'purple',
    supportedFlowTypes: ['atendimento', 'automacao'],
  },
  {
    id: 'buscar-pedido',
    type: 'action',
    category: 'dados',
    title: 'Buscar pedido',
    description: 'Localizar dados de uma venda',
    icon: 'Package',
    color: 'purple',
    supportedFlowTypes: ['atendimento', 'automacao'],
  },
  {
    id: 'buscar-contrato',
    type: 'action',
    category: 'dados',
    title: 'Buscar contrato',
    description: 'Localizar documento contratual',
    icon: 'FileCheck',
    color: 'purple',
    supportedFlowTypes: ['atendimento', 'aprovacao'],
  },
  {
    id: 'exportar-csv',
    type: 'action',
    category: 'dados',
    title: 'Exportar CSV',
    description: 'Gerar arquivo de planilha',
    icon: 'FileDown',
    color: 'purple',
    supportedFlowTypes: ['dados'],
  },
  {
    id: 'importar-csv',
    type: 'action',
    category: 'dados',
    title: 'Importar CSV',
    description: 'Ler dados de uma planilha',
    icon: 'FileUp',
    color: 'purple',
    supportedFlowTypes: ['dados'],
  },
  {
    id: 'transformar-dados',
    type: 'action',
    category: 'dados',
    title: 'Transformar dados',
    description: 'Alterar formato das informações',
    icon: 'Cpu',
    color: 'purple',
    supportedFlowTypes: ['dados', 'integracao'],
  },
  {
    id: 'consolidar-dados',
    type: 'action',
    category: 'dados',
    title: 'Consolidar dados',
    description: 'Agrupar informações de várias fontes',
    icon: 'Combine',
    color: 'purple',
    supportedFlowTypes: ['dados'],
  },

  // Integrações
  {
    id: 'slack',
    type: 'action',
    category: 'integracoes',
    title: 'Slack',
    description: 'Enviar notificações para o Slack',
    icon: 'Hash',
    color: 'indigo',
    supportedFlowTypes: ['automacao', 'notificacao'],
  },
  {
    id: 'google-sheets',
    type: 'action',
    category: 'integracoes',
    title: 'Google Sheets',
    description: 'Ler ou escrever em planilhas Google',
    icon: 'Table',
    color: 'indigo',
    supportedFlowTypes: ['dados', 'automacao'],
  },
  {
    id: 'hubspot',
    type: 'action',
    category: 'integracoes',
    title: 'HubSpot',
    description: 'Sincronizar com HubSpot CRM',
    icon: 'Users',
    color: 'indigo',
    supportedFlowTypes: ['automacao', 'atendimento'],
  },
  {
    id: 'supabase',
    type: 'action',
    category: 'integracoes',
    title: 'Supabase',
    description: 'Operações em banco Supabase',
    icon: 'Database',
    color: 'indigo',
    supportedFlowTypes: ['dados', 'integracao'],
  },
  {
    id: 'stripe',
    type: 'action',
    category: 'integracoes',
    title: 'Stripe',
    description: 'Gerenciar pagamentos Stripe',
    icon: 'CreditCard',
    color: 'indigo',
    supportedFlowTypes: ['automacao', 'dados'],
  },
  {
    id: 'crm-generico',
    type: 'action',
    category: 'integracoes',
    title: 'CRM Genérico',
    description: 'Conectar com qualquer CRM via API',
    icon: 'Layout',
    color: 'indigo',
    supportedFlowTypes: ['automacao', 'atendimento'],
  },
  {
    id: 'webhook-externo',
    type: 'action',
    category: 'integracoes',
    title: 'Webhook Externo',
    description: 'Enviar dados para URL externa',
    icon: 'ExternalLink',
    color: 'indigo',
    supportedFlowTypes: ['integracao', 'automacao'],
  },
  {
    id: 'api-rest',
    type: 'action',
    category: 'integracoes',
    title: 'API REST',
    description: 'Consumir serviços via REST',
    icon: 'Terminal',
    color: 'indigo',
    supportedFlowTypes: ['integracao', 'dados'],
  },
  {
    id: 'planilha-externa',
    type: 'action',
    category: 'integracoes',
    title: 'Planilha Externa',
    description: 'Conectar com arquivos CSV/Excel remotos',
    icon: 'FileSpreadsheet',
    color: 'indigo',
    supportedFlowTypes: ['dados'],
  },
  {
    id: 'erp-generico',
    type: 'action',
    category: 'integracoes',
    title: 'ERP Genérico',
    description: 'Sincronizar dados com ERP',
    icon: 'Briefcase',
    color: 'indigo',
    supportedFlowTypes: ['dados', 'automacao'],
  },

  // Controle
  {
    id: 'aguardar',
    type: 'action',
    category: 'controle',
    title: 'Aguardar',
    description: 'Pausar execução por tempo determinado',
    icon: 'Timer',
    color: 'orange',
    supportedFlowTypes: ['automacao', 'aprovacao'],
  },
  {
    id: 'repeticao',
    type: 'action',
    category: 'controle',
    title: 'Repetição',
    description: 'Executar bloco várias vezes (loop)',
    icon: 'RotateCw',
    color: 'orange',
    supportedFlowTypes: ['automacao', 'dados'],
  },
  {
    id: 'encerrar-fluxo',
    type: 'action',
    category: 'controle',
    title: 'Encerrar fluxo',
    description: 'Finalizar execução imediatamente',
    icon: 'Square',
    color: 'orange',
    supportedFlowTypes: ['automacao', 'aprovacao', 'notificacao', 'integracao', 'atendimento', 'dados'],
  },
  {
    id: 'ramificacao',
    type: 'action',
    category: 'controle',
    title: 'Ramificação',
    description: 'Criar múltiplos caminhos de execução',
    icon: 'GitFork',
    color: 'orange',
    supportedFlowTypes: ['automacao', 'aprovacao'],
  },
  {
    id: 'aprovacao-manual',
    type: 'action',
    category: 'controle',
    title: 'Aprovação manual',
    description: 'Aguardar clique de aprovação de usuário',
    icon: 'UserCheck',
    color: 'orange',
    supportedFlowTypes: ['aprovacao'],
  },
  {
    id: 'pausa-temporaria',
    type: 'action',
    category: 'controle',
    title: 'Pausa temporária',
    description: 'Interromper fluxo até condição externa',
    icon: 'Pause',
    color: 'orange',
    supportedFlowTypes: ['automacao', 'aprovacao'],
  },
  {
    id: 'timeout',
    type: 'action',
    category: 'controle',
    title: 'Timeout',
    description: 'Definir tempo limite para operação',
    icon: 'Hourglass',
    color: 'orange',
    supportedFlowTypes: ['automacao', 'integracao'],
  },
  {
    id: 'retry',
    type: 'action',
    category: 'controle',
    title: 'Retry',
    description: 'Tentar novamente em caso de erro',
    icon: 'Repeat',
    color: 'orange',
    supportedFlowTypes: ['automacao', 'integracao'],
  },
  {
    id: 'paralelizacao',
    type: 'action',
    category: 'controle',
    title: 'Paralelização',
    description: 'Executar várias ações simultaneamente',
    icon: 'Layers',
    color: 'orange',
    supportedFlowTypes: ['automacao', 'dados'],
  },
  {
    id: 'fim-condicional',
    type: 'action',
    category: 'controle',
    title: 'Fim condicional',
    description: 'Encerrar se condição for metida',
    icon: 'StopCircle',
    color: 'orange',
    supportedFlowTypes: ['automacao', 'aprovacao'],
  },
];
