
import { AppThemeMode, WorkflowThemeTokens } from "@/types/theme";

export const workflowThemes: Record<AppThemeMode, WorkflowThemeTokens> = {
  claro: {
    background: "bg-white",
    backgroundSecondary: "bg-slate-50",
    border: "border-slate-200",
    textPrimary: "text-slate-900",
    textSecondary: "text-slate-500",
    accent: "bg-blue-600",
    card: "bg-white",
    hover: "hover:bg-slate-100",
    badge: "bg-slate-100 text-slate-700",
    adminPanel: "bg-white",
    canvas: "bg-slate-50",
    node: "bg-white border-slate-200 shadow-sm",
    connection: "text-slate-300",
  },
  escuro: {
    background: "bg-slate-950",
    backgroundSecondary: "bg-slate-900/50",
    border: "border-slate-800",
    textPrimary: "text-slate-50",
    textSecondary: "text-slate-400",
    accent: "bg-blue-500",
    card: "bg-slate-900/80 backdrop-blur-sm",
    hover: "hover:bg-slate-800",
    badge: "bg-slate-800 text-slate-300",
    adminPanel: "bg-slate-950",
    canvas: "bg-slate-950",
    node: "bg-slate-900/90 border-slate-800 shadow-xl",
    connection: "text-slate-700",
  },
  colorido: {
    background: "bg-indigo-50/30",
    backgroundSecondary: "bg-white/80",
    border: "border-indigo-100",
    textPrimary: "text-indigo-950",
    textSecondary: "text-indigo-600",
    accent: "bg-violet-600",
    card: "bg-white shadow-indigo-100/50",
    hover: "hover:bg-indigo-50",
    badge: "bg-violet-100 text-violet-700",
    adminPanel: "bg-gradient-to-br from-indigo-50 to-white",
    canvas: "bg-[radial-gradient(#e5e7eb_1px,transparent_1px)] bg-indigo-50/20",
    node: "bg-white border-indigo-100 shadow-md",
    connection: "text-indigo-200",
  },
};
