import { supabase } from "@/integrations/supabase/client";

/**
 * Imports tools from a JSON file generated by exportSystemData.
 * Acts as a faithful mirror: re-creates tools, credentials, blocks,
 * knowledge file references and tool links, preserving formatting and lists.
 *
 * Returns a summary with counts of created/skipped tools and any warnings.
 */

export interface ImportResult {
  criadas: number;
  duplicadas: number;
  ignoradas: number;
  erros: string[];
  avisos: string[];
}

const MULTI_PREFIX = "%%MULTI%%";

const serializeMulti = (val: any): string | null => {
  if (val === null || val === undefined) return null;
  if (Array.isArray(val)) {
    if (val.length === 0) return null;
    if (val.length === 1) return String(val[0] ?? "");
    return MULTI_PREFIX + JSON.stringify(val);
  }
  if (typeof val === "string") return val || null;
  return String(val);
};

const asStr = (v: any): string | null => {
  if (v === null || v === undefined) return null;
  const s = typeof v === "string" ? v : String(v);
  return s.length ? s : null;
};

const asArray = (v: any): any[] => (Array.isArray(v) ? v : []);

export async function validateImportJson(content: string): Promise<{ ok: boolean; data?: any; error?: string }> {
  try {
    const data = JSON.parse(content);
    if (!data || typeof data !== "object") return { ok: false, error: "JSON inválido: estrutura raiz inválida." };
    if (!Array.isArray(data.tools)) return { ok: false, error: "JSON inválido: campo 'tools' ausente ou não é uma lista." };
    if (data.tools.length === 0) return { ok: false, error: "JSON não contém nenhuma ferramenta." };
    return { ok: true, data };
  } catch (e: any) {
    return { ok: false, error: `Erro ao ler JSON: ${e.message}` };
  }
}

export async function importSystemData(jsonData: any, userId: string): Promise<ImportResult> {
  const result: ImportResult = { criadas: 0, duplicadas: 0, ignoradas: 0, erros: [], avisos: [] };

  // Pre-fetch existing tools to detect duplicates
  const { data: existingTools } = await supabase
    .from("tools")
    .select("id, titulo")
    .is("deleted_at" as any, null);
  const existingTitles = new Set(
    (existingTools || []).map((t: any) => (t.titulo || "").toLowerCase().trim())
  );

  // Pre-fetch / cache companies
  const { data: existingCompanies } = await supabase.from("companies").select("id, name, slug");
  const companyByName: Record<string, string> = {};
  (existingCompanies || []).forEach((c: any) => {
    companyByName[(c.name || "").toLowerCase().trim()] = c.id;
  });

  // Map of old id → new id (for tool links)
  const idMap: Record<string, string> = {};

  const tools = asArray(jsonData.tools);

  // PASS 1: create tools + credentials + blocks + knowledge file refs
  for (let i = 0; i < tools.length; i++) {
    const t = tools[i];
    try {
      const raw = t._raw?.tool || {};
      const cls = t.classificacao || {};
      const img = t.imagem_capa || {};
      const cred = t.credenciais || {};
      const links = t.links || {};
      const hist = t.historico || {};

      const titulo = (t.nome || raw.titulo || "").toString().trim();
      if (!titulo) {
        result.ignoradas++;
        result.avisos.push(`Ferramenta #${i + 1}: título vazio, ignorada.`);
        continue;
      }

      const isDuplicate = existingTitles.has(titulo.toLowerCase());
      const finalTitulo = isDuplicate ? `COPIA - ${titulo}` : titulo;

      // Resolve company
      let empresaId: string | null = cls.empresa_id || raw.empresa_id || null;
      const empresaNome = (cls.empresa_nome || "").toString().trim();
      if (empresaNome && !empresaId) {
        const key = empresaNome.toLowerCase();
        if (companyByName[key]) {
          empresaId = companyByName[key];
        } else {
          const slug = empresaNome.toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "");
          const { data: newCompany } = await supabase
            .from("companies")
            .insert({ name: empresaNome, slug })
            .select("id")
            .single();
          if (newCompany) {
            empresaId = newCompany.id;
            companyByName[key] = newCompany.id;
          }
        }
      } else if (empresaId) {
        // Verify it exists; if not, fall back by name
        const exists = (existingCompanies || []).some((c: any) => c.id === empresaId);
        if (!exists) empresaId = null;
      }

      // Build tool insert payload (preserve formatting via raw strings)
      const toolPayload: any = {
        titulo: finalTitulo,
        descricao: t.descricao ?? raw.descricao ?? "",
        funcao: t.funcao ?? raw.funcao ?? null,
        instrucoes: t.instrucoes ?? raw.instrucoes ?? "",
        categoria: cls.categoria || raw.categoria || null,
        tool_type: cls.tool_type || raw.tool_type || "gpt",
        setores: cls.setor_departamento || raw.setores || "Todas as ferramentas",
        tags: Array.isArray(cls.tags) ? cls.tags : (Array.isArray(raw.tags) ? raw.tags : []),
        empresa_id: empresaId,
        image_url: img.url || raw.image_url || null,
        cor_cartao: img.cor_cartao || raw.cor_cartao || null,
        print_processo_url: img.print_processo_url || raw.print_processo_url || null,
        print_resultado_url: img.print_resultado_url || raw.print_resultado_url || null,
        link_acesso_original: links.acesso || raw.link_acesso_original || null,
        link_contexto: links.contexto || raw.link_contexto || null,
        link_criacao_prompt: links.criacao_prompt || raw.link_criacao_prompt || null,
        link_gpt_criacao_prompt: links.gpt_criacao_prompt || raw.link_gpt_criacao_prompt || null,
        link_gpt_pronto: links.gpt_pronto || raw.link_gpt_pronto || null,
        link_gpt_transformacao_contexto: links.gpt_transformacao_contexto || raw.link_gpt_transformacao_contexto || null,
        link_gpt_transformacao_base_conhecimento: links.gpt_transformacao_base_conhecimento || raw.link_gpt_transformacao_base_conhecimento || null,
        link_contexto_transformacao_base_conhecimento: links.contexto_transformacao_base_conhecimento || raw.link_contexto_transformacao_base_conhecimento || null,
        links_producao: links.links_producao || raw.links_producao || {},
        modelo_recomendado: t.modelo_recomendado || raw.modelo_recomendado || null,
        recursos: t.itens_marcados || raw.recursos || {},
        quebra_gelos: Array.isArray(t.quebra_gelos) ? t.quebra_gelos : (Array.isArray(raw.quebra_gelos) ? raw.quebra_gelos : []),
        acoes: Array.isArray(hist.acoes) ? hist.acoes : (Array.isArray(raw.acoes) ? raw.acoes : []),
        status: t.status || raw.status || "draft",
        is_archived: !!t.is_archived,
        origem: hist.origem || raw.origem || "import-json",
        origem_detalhe: hist.origem_detalhe || raw.origem_detalhe || `Importado em ${new Date().toISOString().slice(0,10)}`,
        imported_from_file_name: hist.imported_from_file_name || raw.imported_from_file_name || null,
        version_number: hist.version_number || raw.version_number || 1,
        criado_por: userId,
        atualizado_por: userId,
      };

      const { data: insertedTool, error: insertErr } = await supabase
        .from("tools")
        .insert(toolPayload)
        .select("id")
        .single();

      if (insertErr || !insertedTool) {
        result.ignoradas++;
        result.erros.push(`"${titulo}": ${insertErr?.message || "falha ao inserir"}`);
        continue;
      }

      const newId = insertedTool.id;
      if (t.id) idMap[t.id] = newId;

      // Credentials
      const rawCred = t._raw?.credentials || {};
      const apis = asArray(cred.apis);
      const apiValues = apis.map((a: any) => a?.valor ?? "");
      const apiLabels = apis.map((a: any, idx: number) => ({ nome: a?.nome ?? `API ${idx + 1}` }));

      const urlsArr = Array.isArray(cred.urls) && cred.urls.length ? cred.urls : (cred.url ? [cred.url] : []);

      const credPayload: any = {
        tool_id: newId,
        credential_email: cred.email || cred.login || rawCred.credential_email || null,
        credential_senha: cred.senha || rawCred.credential_senha || null,
        credential_url: serializeMulti(urlsArr.length ? urlsArr : (rawCred.credential_url ?? null)),
        credential_anon_public: cred.keys?.anon_public || rawCred.credential_anon_public || null,
        credential_publish_key: cred.keys?.publish_key || rawCred.credential_publish_key || null,
        credential_secret_key: cred.keys?.secret_key || rawCred.credential_secret_key || null,
        credential_service_role: cred.keys?.service_role || rawCred.credential_service_role || null,
        credential_project_id: cred.keys?.project_id || rawCred.credential_project_id || null,
        credential_api: apiValues.length ? serializeMulti(apiValues) : (rawCred.credential_api ?? null),
        api_labels: apiLabels.length ? apiLabels : (Array.isArray(rawCred.api_labels) ? rawCred.api_labels : []),
        prompt_final: t.prompt ?? rawCred.prompt_final ?? null,
      };

      const hasAnyCred = Object.entries(credPayload).some(([k, v]) =>
        k !== "tool_id" && v !== null && v !== "" && !(Array.isArray(v) && v.length === 0)
      );
      if (hasAnyCred) {
        const { error: cErr } = await supabase.from("tool_credentials").insert(credPayload);
        if (cErr) result.avisos.push(`"${titulo}": credenciais não inseridas (${cErr.message})`);
      }

      // Blocks
      const blocos = asArray(t.blocos);
      if (blocos.length) {
        const blocksPayload = blocos.map((b: any) => ({
          tool_id: newId,
          block_type: b.block_type || "short_text",
          titulo: b.titulo ?? "",
          descricao: b.descricao ?? null,
          conteudo: b.conteudo ?? null,
          ordem: typeof b.ordem === "number" ? b.ordem : 0,
          aba: b.aba || "configurar",
          visibility_visitor: b.visibility_visitor !== false,
          visibility_reader: b.visibility_reader !== false,
          visibility_editor: b.visibility_editor !== false,
          storage_path: b.storage_path || null,
        }));
        const { error: bErr } = await supabase.from("tool_blocks").insert(blocksPayload);
        if (bErr) result.avisos.push(`"${titulo}": blocos não inseridos (${bErr.message})`);
      }

      // Knowledge file references (metadata only — actual binary stays at original storage)
      const arquivos = asArray(t.base_conhecimento?.arquivos);
      if (arquivos.length) {
        const filesPayload = arquivos
          .filter((f: any) => f.storage_path)
          .map((f: any) => ({
            tool_id: newId,
            file_name: f.nome || "arquivo",
            description: f.descricao || "",
            storage_path: f.storage_path,
            is_archived: !!f.is_archived,
            uploaded_by: userId,
          }));
        if (filesPayload.length) {
          const { error: kfErr } = await supabase.from("knowledge_files").insert(filesPayload);
          if (kfErr) result.avisos.push(`"${titulo}": arquivos não inseridos (${kfErr.message})`);
        }
      }

      existingTitles.add(finalTitulo.toLowerCase());

      if (isDuplicate) {
        result.duplicadas++;
        result.avisos.push(`"${titulo}": duplicata, criada como "COPIA - ${titulo}"`);
      } else {
        result.criadas++;
      }
    } catch (err: any) {
      result.ignoradas++;
      result.erros.push(`Item #${i + 1}: ${err?.message || String(err)}`);
    }
  }

  // PASS 2: tool_links (after all tools have new ids)
  for (const t of tools) {
    const sourceNew = t.id ? idMap[t.id] : null;
    if (!sourceNew) continue;
    const vinc = asArray(t.ferramentas_vinculadas);
    for (const v of vinc) {
      const targetNew = v?.id ? idMap[v.id] : null;
      if (!targetNew) continue;
      try {
        await supabase.from("tool_links").insert({
          source_tool_id: sourceNew,
          target_tool_id: targetNew,
          link_type: v.link_type || "depends_on",
        });
      } catch {
        /* ignore link errors */
      }
    }
  }

  return result;
}
